### ISSUE TITLE
[Feature] Fretboard Memorization Game

### ISSUE THREAD

**Issue by justinhhorner** [whitep4nth3r/fretonator#88]
How about some game development for Fretonator? 🙂🎮

This seems like the perfect project for a simple fretboard memorization game where a random note is selected, and the player attempts to identify the note correctly. Each game session can keep up with the correct and incorrect count.

I'm not yet familiar enough to know how difficult it would be to accomplish this using the fretonator component.

I'd love to know your thoughts on this idea.

**Comment by whitep4nth3r** [comment]
Justin, I love this idea. 

Personally, I'm incredibly unfamiliar with how to manage state in Angular applications, so I wouldn't know where to start myself. 

My guess at whether the current component would be compatible... I think it would end up complicating the scalability of the current component (extra tunings, more strings? etc), so if you wanted to do a proof of concept, it might be best creating a secondary component and keeping game functionality separate ... (can one component extend another in Angular??)

Further more it should probably be on a different route. I was thinking that the LEARN area is rubbish and stale, so maybe we need a /7-note route and a /game route or whatever, rather than the current learning hub which takes you down a weird rabbit hole of nothingness.
